name: Daily Newsletter Automation
on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC (10:00 AM IST)
  workflow_dispatch:

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        continue-on-error: true

      # - name: Run newsletter script
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: |
      #     python main.py || echo "Exit code: $?"
      #   continue-on-error: true

      - name: Run send script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        run: |
          python send.py || echo "Send script exited with code: $?"
        continue-on-error: true

  commit-changes:
    needs: generate-newsletter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Add newsletter files for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}